# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Kevin Kallin Blogg'
tagline:          'A Metro theme for Jekyll'
description:      'A Sample blog using Jekyll Metro'
url:              'https://kevinkallin.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Kevin Kallin'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/Cescolainen'
flickr:
github:         'https://github.com/kevinkallin'
gplus:          'https://plus.google.com/100425464897246255887/'
instagram:
pinterest:
linkedin:       'https://www.linkedin.com/in/kevin-kallin-82947812a/'
rss:
stackoverflow:  'http://stackoverflow.com/users/185655/abdel-raoof'
twitter:        'https://twitter.com/olakara'

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
